---
update_stale_players:
  cron: '* * * * *'
  class: 'Observatory::StalePlayersUpdate'
  queue: stale_players_update
  args:
  description: 'Schedule update for all players with stale data'

clear_update_scheduled_at:
  cron: '* * * * *'
  class: 'Observatory::ClearUpdateScheduledAt'
  queue: clear_update_scheduled_at
  args:
  description: 'Clears `update scheduled at` flag after certain time passed'

delete_invalid_players:
  cron: '* * * * *'
  class: 'Observatory::DeleteInvalidPlayers'
  queue: delete_invalid_players
  args:
  description: 'Deletes players for whom no data could be retrieved'

expire_old_player_data_exports:
  cron: '* * * * 0'
  class: 'Observatory::ExpireOldPlayerDataExports'
  queue: expire_old_player_data_exports
  args:
  description: 'Deletes old player exports'

update_leaderboard:
  cron: '*/5 * * * *'
  class: 'Observatory::LeaderboardUpdate'
  queue: leaderboard_update
  args:
  description: 'Updates leaderboard'

nsl_accounts_sync:
  cron: '1 * * * *'
  class: 'Observatory::NSLAccountsSync'
  queue: nsl_accounts_sync
  args:
  description: 'Updates NSL accounts cache'
